name: Create new version

on:
  workflow_dispatch:
    inputs:
      dockerTag:
        description: 'What tag to build a release for'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create new branch for version
        run: git branch ${{ github.event.inputs.dockerTag }}


        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.inputs.dockerTag }}