name: Create new version

on:
  workflow_dispatch:
    inputs:
      dockerTag:
        description: 'What tag to build a release for'
        required: true
        
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create new branch for version
        run: git branch ${{ github.event.inputs.dockerTag }}
      - name: Add test file
        run: touch testFile 
      - name: commit files
        run: git add --all && git commit -m 'Initialize ${{ github.event.inputs.dockerTag }} branch'
      - name: Push new branch
        run: git push
