name: Config

on:
  workflow_dispatch:
  #schedule:
  #  - '30 5,17 * * *'

jobs:
  test:
    name: Generate nwn files
    runs-on: ubuntu-latest
    steps:
      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      - name: Download NeverwinterNights windows
        run: |
          steamcmd +login ${{ secrets.STEAM_USER }} ${{ secrets.STEAM_PASS }} 704451 validate +quit
      - run: |
          steamcmd +force_install_dir ../data/ 704451 validate +quit
