name: Config

on:
  workflow_dispatch:
  #schedule:
  #  - '30 5,17 * * *'

jobs:
  test:
    name: Generate nwn files
    runs-on: ubuntu-latest
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v3
      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      - name: Download NeverwinterNights
        run: steamcmd app_update 704450 validate +login ${{ secrets.STEAM_USER }} ${{ secrets.STEAM_PASS }} +force_install_dir +quit