name: Config

on:
  workflow_dispatch:
  #schedule:
  #  - '30 5,17 * * *'

jobs:
  test:
    name: Generate nwn files
    runs-on: ubuntu-latest
    steps:
      - name: Setup steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
      - name: Download NeverwinterNights windows
        run: steamcmd +@sSteamCmdForcePlatformType linux +force_install_dir ./depot_data/ +login ${{ secrets.STEAM_USER }} ${{ secrets.STEAM_PASS }} +app_update 704451 validate +quit
      #- name: Checkout
      #  uses: actions/checkout@v3