name: Generate

on:
  workflow_dispatch:
  #schedule:
  #  - '30 5,17 * * *'

jobs:
  test:
    name: Generate nwn files
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh repo clone SteamRE/DepotDownloader

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: |
          cd DepotDownloader/DeplotDownloader
          dotnet run -app 704451 -username ${{ secrets.STEAM_USER }} -password ${{ secrets.STEAM_PASS }}
