name: Generate

on:
  workflow_dispatch:
    inputs:
      release-branch:
        type: string
        description: steam branch name to use, See https://steamdb.info/app/704450/depots/
        required: true
        default: preview

jobs:
  generate:
    name: Generate nwn files
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: '1.6.0' # default is 'stable'
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - name: Clone SteamRE/DepotDownloader
        run: |
          cd ..
          gh repo clone SteamRE/DepotDownloader
      - name: Download preview nwn:ee files
        if: github.event.inputs.release-branch == 'preview'
        run: |
          cd ../DepotDownloader/DepotDownloader
          dotnet run -app 704450 -depot 704451 -beta ${{ github.event.inputs.release-branch }} -betapassword ${{ github.event.inputs.release-branch }}${{ github.event.inputs.release-branch }} -username ${{ secrets.STEAM_USER }} -password ${{ secrets.STEAM_PASS }}
          cd ../..
          mkdir out && mkdir out/${{ github.event.inputs.release-branch }}
      - name: Download nwn:ee files
        if: github.event.inputs.release-branch != 'preview'
        run: |
          cd ../DepotDownloader/DepotDownloader
          dotnet run -app 704450 -depot 704451 -beta ${{ github.event.inputs.release-branch }} -username ${{ secrets.STEAM_USER }} -password ${{ secrets.STEAM_PASS }}
          cd ../..
          mkdir out && mkdir out/${{ github.event.inputs.release-branch }}
      - run: |
          nimble install nasher -y
          nasher unpack --file:depots/704451/7843474/data/nwn_base.key ../out/${{ github.event.inputs.release-branch }}