name: Upload-NWN-Assets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: docker://urothis/nwn-assets:latest
      - name: pull latest nwn assets
        run: ls .
          ls /
          ls /extracted
