name: Upload-NWN-Assets

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: pull latest nwn assets
        uses: docker://urothis/nwn-assets:latest

      - name: testing
        run: ls .
          ls /
          ls /extracted
