name: Upload-NWN-Assets

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: docker://urothis/nwn-assets:latest
    steps:
      - uses: actions/checkout@v2
      - name: pull latest nwn assets
        run: |
          cp -r /extracted/ ${GITHUB_WORKSPACE}/key-file/
      - uses: stefanzweifel/git-auto-commit-action@v4
