name: Upload-NWN-Assets

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    container:
      image: docker://urothis/nwn-assets:latest
    steps:
      - uses: actions/checkout@v2
      - name: pull latest nwn assets
        run: |
          cp -R /extracted /github/key-file
      - uses: EndBug/add-and-commit@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
